### ISSUE TITLE
MMarkdown

### ISSUE THREAD

**Issue by vinceyoumans** [spech66/bootstrap-bp-hugo-theme#10]
I am getting this warning...   

```
Markup type mmark is deprecated and will be removed in a future release. See https://gohugo.io//content-management/formats/#list-of-content-formats
```

how do I resolve this?  to get rid of warning?

**Comment by spech66** [comment]
This is because of the sample file. You can just delete it if you want.

`https://github.com/spech66/bootstrap-bp-hugo-theme/blob/master/exampleSite/content/post/math-typesetting.mmark`
