### ISSUE TITLE
Rendering of terms, .Data.Terms, with $key

### ISSUE THREAD

**Issue by frm24p** [spech66/bootstrap-bp-hugo-theme#18]
In file `terms.html`, `terms` are rendered. `<h2 id="{{ $key | urlize }}">{{ $key }}</h2>` appears.

A term as given in the source of the post is not displayed literally. For example `blue sky` is converted to  `blue-sky` in `$key`. This is usefull for the sorting and searching, but not for rendering. It would be nice see `blue sky` in the heading.

The trouble hits international users more than english users.

**Comment by spech66** [comment]
I guess my original thoughts was to have it more like a tag view instead of the real names but I think your solution is more user friendly.

**Comment by spech66** [comment]
Fixed. Will be in the next Release

https://github.com/spech66/bootstrap-bp-hugo-theme/commit/d6facd6a7d798f62be25a65432951931858e089f
