### ISSUE TITLE
Footer limits Copyright to current year

### ISSUE THREAD

**Issue by mschilli87** [spech66/bootstrap-bp-hugo-theme#19]
Happy New Year!

I noticed that the footer only lists the current year for the copyright.
Is there any way to list a range to cover old content as well?

I could imagine a solution that adds a new config variable which is used in https://github.com/spech66/bootstrap-bp-hugo-theme/blob/master/layouts/partials/footer.html#L32 that simply defaults to `{{ now.Format "2006" }}` but allow to set something like `"2023 - 2024"` explicitely.

If you know a way to determine the correct year range automatically that would be great of course but I wouldn't mind updating a site parameter once a year. 😉 

Would you be up for a change like this? If so should I attemt a PR or do you prefer implementing your own solution?

**Comment by spech66** [comment]
Actually I struggle with this every year and I'm not sure what the correct approach would be. Currently I update my pages every year so it only shows the current year like GitHub does in the footer.

**Comment by mschilli87** [comment]
Would you be open for adding `Site.Params.CopyrightYears` defaulting to the current year as per my suggestion above? If so, I can give it a try and submit a PR ASAP.

**Comment by spech66** [comment]
Sure, always glad for improvements :smile:
