### ISSUE TITLE
Missing Tiktok social icon

### ISSUE THREAD

**Issue by bob3000** [spech66/bootstrap-bp-hugo-theme#24]
Hey Sebastian, thanks for your awesome theme!

I had trouble getting a social link with a proper Tiktok icon to work. I'm a frontend noob and a bit stuck here. Would you mind adding the icon or giving me a hint on how to do it?

Thanks 🙏🏻

**Comment by spech66** [comment]
Added TT to the latest release. Just add this to the social section:
```
tiktok = "@xyz"
```
