### ISSUE TITLE
Change Colors

### ISSUE THREAD

**Issue by sciarrilli** [spech66/bootstrap-bp-hugo-theme#4]
Hello,

Could you please explain how to change the color of the font awesome icons? Also what is the syntax to apply themeColor?

Regards,
Nick

**Comment by spech66** [comment]
Every color/theme has it's own file in `https://github.com/spech66/bootstrap-bp-hugo-theme/tree/master/assets/css`. You can copy or generate them according to `https://github.com/spech66/bootstrap-bp-hugo-theme/blob/master/assets/css/info.txt`.

Just at a css styling for the fa* classes to your css for font-awesome.

**Comment by sciarrilli** [comment]
Hi Seb,

Sorry if I am a little slow. New to hugo. I see the different css's in the assets folder. 

Where do I copy the css file to? 
Is it a setting I use in config.toml?

Thanks,
Nick

**Comment by spech66** [comment]
So I try to give you some deeper insights that might be helpful :-)

You should have your directory structure like `https://gohugo.io/getting-started/directory-structure/`. The theme should be below the themes folder. You can now add your css to the themes/bootstrap-bp-hugo-theme/assets/css folder or create you own assets/css folder in your main directory structure. Hugo will look in both folders for files.

The `themeColor` variable is a setting for your config file. What the theme does is basically this:
* Look for /css/bootstrap-THEMECOLOR.min.css
* Look for /css/main-THEMECOLOR.css
* and some other files
* generate a combined css file to use

If you want to see how this works in code you might want to have a look in the file: `https://github.com/spech66/bootstrap-bp-hugo-theme/blob/master/layouts/partials/head.html`
