### ISSUE TITLE
Missing spanish i18n support.

### ISSUE THREAD

**Issue by ErickCastellanos** [spech66/bootstrap-bp-hugo-theme#7]
There is no spanish i18n file.
I'll create a pull request for that.

**Comment by spech66** [comment]
Thank you very much for the spanish translation! :)

Have a nice day!

**Comment by spech66** [comment]
Will add those to https://github.com/spech66/materialize-bp-hugo-theme as well.

**Comment by ErickCastellanos** [comment]
Glad to help in both repositories! I did it in the spirit of Hacktoberfest. So, if you find my contribution useful, could you please tag my PR with the "hacktoberfest-accepted" label? It will make it appear in my Hacktober contributions. Thanks!
( PR #8 )
